from setuptools import setup

setup(name='ipcv_compression',
      version='0.0.1',
      description='Compression Excerise.',
      url='https://github.com/vl0w/IPCV-Compression',
      author='Michael Zurmühle, Jonas Hansen',
      author_email='michael.zurmuehle@stud.hslu.ch; jonas.hansen@stud.hslu.ch',
      license='MIT',
      packages=['ah3k_management',
                'ah3k_management.shared',
                'ah3k_management.container_recognition.interface',
                'ah3k_management.container_recognition',
                'ah3k_management.controller_adapter.interface',
                'ah3k_management.controller_adapter',
                'ah3k_management.line_detection.interface',
                'ah3k_management.line_detection',
                'ah3k_management.operator',
                'ah3k_management.operator.actions',
                'ah3k_management.operator.inputs',
                'ah3k_management.processing',
                'ah3k_management.user_interaction'],
      scripts=['bin/ah3k'],
      zip_safe=False)